use_frameworks!

target 'TDModalAlert_Example' do
  pod 'TDModalAlert', :path => '../'

  target 'TDModalAlert_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
